### PR TITLE
neni nutno, whats up, floydi a cudzinka

### PR DESCRIPTION
**Pull request by dhodovsk**
New songs added:

 - 4 Non Blondes - What's Up
 - Pink Floyd - Wish You Were Here
 - Zdenek Sverak, Jaroslav Uhlir - Neni nutno
 - Xindl X, Mirka Miskechova - Cudzinka v Tvojej Zemi

### CODE REVIEW

**Comment by ingvagabund** [comment]
@dhodovsk Can you do one song = one PR? :)

**Comment by dhodovsk** [comment]
Will do :)

**Comment by dhodovsk** [comment]
Just one question @ingvagabund

How do we deal with generated pdf, when there are multiple PR's with songs opened?
 - when the songbook.pdf file is included in every PR, it will create merge conflict
 - when it is not included in PR's, we need to make sure to update it with the songs of merged PR's

**Comment by pirat89** [comment]
@dhodovsk The generated pdf should be removed from the repository. The best solution here would be put it as asset to the release or release draft. So the repository will not be messed up by the pdf.

**Comment by pirat89** [comment]
@dhodovsk I will look at it tonight as I can't go outside and will try to fix format of generated pdf as well.

**Comment by ingvagabund** [comment]
> How do we deal with generated pdf, when there are multiple PR's with songs opened?

Do not generate the pdf file

**Pull request closed without merging**
